/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * buscardisponibilidad.java
 *
 * Created on 24/11/2011, 11:11:33 AM
 */

package visual;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.control.pasajecontrol;
import negocio.control.viajecontrol;
import negocio.exceptions.PreexistingEntityException;
import datos.Viaje;
import negocio.control.fecha;
/**
 *
 * @author Administrador
 */
public class buscardisponibilidad extends javax.swing.JDialog {
private addreservac res;
private String destino;
private String dias;
private String mes;
private String year;
private String hora;
private String min;
private Object f;
    /** Creates new form buscardisponibilidad */
    public buscardisponibilidad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
res = new addreservac(parent, modal) ;
jButton2.setVisible(false);
    }

    buscardisponibilidad() {
      
    }
    public String getDestino(){
        destino = String.valueOf(jComboBox1.getSelectedItem());
        return destino;
    }
  
   
    
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(reservacionastro.ReservacionastroApp.class).getContext().getResourceMap(buscardisponibilidad.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setUI(null);
        jTextField1.setName("jTextField1"); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pinar del Rio", "Habana", "Matanzas", "Ciego deAvila", "Cienfuegos", "Villa Clara", "Camaguey", "Holguin", "Las Tunas", "Granma", "Santiago de Cuba", "Guantanamo" }));
        jComboBox1.setName("jComboBox1"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pr.setText(resourceMap.getString("pr.text")); // NOI18N
        pr.setName("pr"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jSpinner1.setModel(new javax.swing.SpinnerDateModel());
        jSpinner1.setName("jSpinner1"); // NOI18N

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jComboBox2.setName("jComboBox2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                                            .addGap(128, 128, 128)
                                            .addComponent(jTextField1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(43, 43, 43)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(jLabel1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(pr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)))
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(137, 137, 137)
                                .addComponent(jButton2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public Viaje idreservar() throws PreexistingEntityException, Exception{
   String diass = "";
            String anos = "";
            String horas = "";
            String mins = "";
            String mess = "";
            fecha fecha = new fecha();
            f = jSpinner1.getValue();
            String arreglo = String.valueOf(f);
            diass = fecha.diaSalida(arreglo);
            anos = fecha.AnoSalida(arreglo);
            horas = fecha.HoraSalida(arreglo);
            mins = fecha.MinSalida(arreglo);
            mess = fecha.MesSalida(arreglo);
    Viaje x=new Viaje() ;
    int idres=0;
    viajecontrol vc = new viajecontrol();
    idres=vc.buscaridp(String.valueOf(jComboBox1.getSelectedItem()), diass, String.valueOf(jComboBox2.getSelectedItem()), anos, horas, mins);
        try {
            x = vc.buscar(idres);
        } catch (Exception ex) {
            Logger.getLogger(buscardisponibilidad.class.getName()).log(Level.SEVERE, null, ex);
        }
    return x;
}

public int id() throws PreexistingEntityException, Exception{
    String diass = "";
            String anos = "";
            String horas = "";
            String mins = "";
            String mess = "";
            fecha fecha = new fecha();
            f = jSpinner1.getValue();
            String arreglo = String.valueOf(f);
            diass = fecha.diaSalida(arreglo);
            anos = fecha.AnoSalida(arreglo);
            horas = fecha.HoraSalida(arreglo);
            mins = fecha.MinSalida(arreglo);
            mess = fecha.MesSalida(arreglo);
    viajecontrol vc = new viajecontrol();
    int id=vc.buscaridp(String.valueOf(jComboBox1.getSelectedItem()), diass, String.valueOf(jComboBox2.getSelectedItem()), anos, horas, mins);
return id;

}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String diass = "";
            String anos = "";
            String horas = "";
            String mins = "";
            String mess = "";
            fecha fecha = new fecha();
            f = jSpinner1.getValue();
            String arreglo = String.valueOf(f);
            diass = fecha.diaSalida(arreglo);
            anos = fecha.AnoSalida(arreglo);
            horas = fecha.HoraSalida(arreglo);
            mins = fecha.MinSalida(arreglo);
            mess = fecha.MesSalida(arreglo);
            try {
                viajecontrol vc = new viajecontrol();
                pasajecontrol p = new pasajecontrol();
                int id = 0;
                id = vc.buscaridp(String.valueOf(jComboBox1.getSelectedItem()), diass, String.valueOf(jComboBox2.getSelectedItem()), anos, horas, mins);
                if (id == 0) {
                    JOptionPane.showMessageDialog(this, "No existe el viaje");
                } else {
                    if (p.cantPasajesD(id) > 0) {
                        JOptionPane.showMessageDialog(this, "Hay pasajes disponibles");
                        jButton2.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "No hay pasajes disponibles para el viaje deseado");
                    }
                    // TODO add your handling code here:
                    int cant = 0;
                    cant = p.cantPasajesD(id);
                    //  JOptionPane.showMessageDialog(this, "Hay pasajes disponibles");
                    pr.setText(String.valueOf(cant));
                }
            } catch (PreexistingEntityException ex) {
                Logger.getLogger(buscardisponibilidad.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(buscardisponibilidad.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (PreexistingEntityException ex) {
            Logger.getLogger(buscardisponibilidad.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(buscardisponibilidad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

addreservac r =new addreservac(null, true);
     r.setVisible(true);
     setVisible(false);
// TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
    destino d= new destino(null,true);
    d.setVisible(true);
setVisible(false);
}//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField pr;
    // End of variables declaration//GEN-END:variables

}
