/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RectificarR.java
 *
 * Created on 5/06/2012, 11:14:57 AM
 */

package visual.listaespera;

import datos.Listaespera;
import datos.Pasaje;
import datos.Pasajesle;
import datos.Pasajesrectificados;
import datos.Reservacion;
import datos.Reservacionle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.control.fecha;
import negocio.control.meses;
import negocio.control.pasajecontrol;
import negocio.control.reservacioncontrol;
import negocio.control.viajecontrol;
import negocio.exceptions.PreexistingEntityException;
import negocio.jpa.ListaesperaJpaController;
import negocio.jpa.PasajesleJpaController;
import negocio.jpa.PasajesrectificadosJpaController;
import negocio.jpa.ReservacionleJpaController;
import negocio.jpa.exceptions.NonexistentEntityException;

/**
 *
 * @author MiPC
 */
public class RectificarR extends javax.swing.JDialog {
private Object f;
private Object list;
private String ruta="";
private Object reservada="reservada";

private String destinocci[]= {"Villa Clara","Matanzas","La Habana","Mayabeque","Atemisa","Pinar del Rio"};
    /** Creates new form RectificarR */
    public RectificarR(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTextField1.setVisible(false);
        jLabel3.setVisible(false);
        jButton2.setVisible(false);
        jButton4.setVisible(false);
        jButton3.setVisible(false);
        jButton5.setVisible(false);
       jButton6.setVisible(false);
         jButton7.setVisible(false);
          jButton9.setVisible(false);
          jButton11.setVisible(false);
            jButton12.setVisible(false);
         jList1.setVisible(false);
         jComboBox2.setVisible(false);
         jLabel5.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jButton12 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setName("jLabel2"); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pinar del Rio", "Habana", "Matanzas", "Ciego deAvila", "Cienfuegos", "Villa Clara", "Camaguey", "Holguin", "Las Tunas", "Granma", "Santiago de Cuba", "Guantanamo" }));
        jComboBox1.setName("jComboBox1"); // NOI18N

        jSpinner1.setModel(new javax.swing.SpinnerDateModel());
        jSpinner1.setName("jSpinner1"); // NOI18N

        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setName("jTextField1"); // NOI18N

        jLabel3.setName("jLabel3"); // NOI18N

        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setName("jLabel4"); // NOI18N

        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jList1.setName("jList1"); // NOI18N
        jScrollPane1.setViewportView(jList1);

        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setName("jButton8"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setName("jButton9"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setName("jButton10"); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setName("jButton11"); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pinar del Rio", "Habana", "Matanzas", "Ciego deAvila", "Cienfuegos", "Villa Clara", "Camaguey", "Holguin", "Las Tunas", "Granma", "Santiago de Cuba", "Guantanamo" }));
        jComboBox2.setName("jComboBox2"); // NOI18N

        jButton12.setName("jButton12"); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel5.setName("jLabel5"); // NOI18N

        jButton13.setName("jButton13"); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jTextField2.setName("jTextField2"); // NOI18N

        jButton14.setName("jButton14"); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1))
                                    .addComponent(jButton2)
                                    .addComponent(jButton5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jButton13))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(117, 117, 117)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(27, 27, 27)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                                    .addGap(87, 87, 87))
                                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton13)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public int nroviaje() throws PreexistingEntityException, Exception{
     viajecontrol vc = new viajecontrol();
            String diass = "";
            String anos = "";
            String horas = "";
            String mins = "";
            String mess = "";
            fecha fecha = new fecha();
            meses m= new meses();
            String mes= "";
            Pasajesrectificados p = new Pasajesrectificados();
              f = jSpinner1.getValue();
            String arreglo = String.valueOf(f);
            diass = fecha.diaSalida(arreglo);
            anos = fecha.AnoSalida(arreglo);
            horas = fecha.HoraSalida(arreglo);
            mins = fecha.MinSalida(arreglo);
            mess = fecha.MesSalida(arreglo);
            mes = m.getMes(mess);
            int nurov=0;
             nurov=vc.buscaridp(String.valueOf(jComboBox1.getSelectedItem()), diass,mes, anos,horas,mins);
          return nurov;

}
/*public void setp(){
  this.pos=0;
}*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            viajecontrol vc = new viajecontrol();
            String diass = "";
            String anos = "";
            String horas = "";
            String mins = "";
            String mess = "";
            fecha fecha = new fecha();
            meses m= new meses();
            String mes= "";
            Pasajesrectificados p = new Pasajesrectificados();
            PasajesrectificadosJpaController pr = new PasajesrectificadosJpaController();
            reservacioncontrol rc = new reservacioncontrol();
            f = jSpinner1.getValue();
            String arreglo = String.valueOf(f);
            diass = fecha.diaSalida(arreglo);
            anos = fecha.AnoSalida(arreglo);
            horas = fecha.HoraSalida(arreglo);
            mins = fecha.MinSalida(arreglo);
            mess = fecha.MesSalida(arreglo);
            mes = m.getMes(mess);
            int nurov=0;
            int nror=0;
            nurov=vc.buscaridp(String.valueOf(jComboBox1.getSelectedItem()), diass,mes, anos,horas,mins);
          // jTextField2.setText(String.valueOf(nurov));
            if (nurov==0)
                JOptionPane.showMessageDialog(this, "No existe el viaje");
            if(nurov!=0){
                jTextField1.setVisible(true);
                jLabel3.setVisible(true);
                jButton2.setVisible(true);
                jButton1.setVisible(false);
                jButton5.setVisible(true);
        // jButton4.setVisible(true);
        //   jButton3.setVisible(true);
            }



        } catch (PreexistingEntityException ex) {
            Logger.getLogger(RectificarR.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(RectificarR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            int nrov = 0;
            nrov = nroviaje();
            Pasajesrectificados p = new Pasajesrectificados();
            PasajesrectificadosJpaController pr = new PasajesrectificadosJpaController();
            int nror=0;
            reservacioncontrol rc = new reservacioncontrol();
        //    jTextField2.setText(String.valueOf(nrov));

                      for (int i = 0; i < rc.listar1().size(); i++) {
                Reservacion object = rc.listar1().get(i);
                if(jTextField1.getText().equals(object.getCi())
                        && nrov==object.getViaje().getNroviaje()){
                    object.setRectificada("si");
                    nror++;
                    rc.actualizar(object);break;

                }


            }
                  //  jTextField3.setText(String.valueOf(nror));
            if(nror==0)
    JOptionPane.showMessageDialog(this, "No existe la reservación");
        /*    if(nror!=0){

                 p.setNroreserv(nror);
        pr.create(p);*/
            else
        JOptionPane.showMessageDialog(this, "Reservación rectificada");
           // }

        } catch (PreexistingEntityException ex) {
            Logger.getLogger(RectificarR.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(RectificarR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
           
         //   int cantreserv = 0;
             int psobrant=0;
            PasajesleJpaController ple= new PasajesleJpaController();
           Pasajesle p = new Pasajesle();
        //    pasajecontrol pc = new pasajecontrol();
            reservacioncontrol rc = new reservacioncontrol();
          



         
            for (int j = 0; j < rc.listar1().size(); j++) {
                  Reservacion object3 = rc.listar1().get(j);
                     if(object3.getViaje().getNroviaje()==nroviaje()
                            && object3.getRectificada().equals("no")){
                       
                    
                         p.setAsiento(object3.getAsiento());
                    p.setDiasalida(object3.getDiasalida());
                    p.setHora(object3.getHorasalida());
                    p.setMes(object3.getMessalida());
                    p.setMin(object3.getMinutosalida());
                    p.setPrecio(object3.getPrecio());
                    p.setRuta(object3.getViaje().getRuta());
                    p.setYear(object3.getYearsalida());
                    p.setDisponible("si");

                ple.create(p);
                object3.setRectificada("trasmitida");
                rc.actualizar(object3);
                psobrant++;
               } 
            }

if(psobrant==0)
    JOptionPane.showMessageDialog(this, "No hay fallos");
    else
 JOptionPane.showMessageDialog(this, "Los pasajes fallos han sido asigandos a LE");
jButton3.setVisible(false);
jButton6.setVisible(true);


        } catch (PreexistingEntityException ex) {
            Logger.getLogger(RectificarR.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(RectificarR.class.getName()).log(Level.SEVERE, null, ex);

            }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            int cantreserv = 0;
            int psobrant = 0;
            PasajesleJpaController ple = new PasajesleJpaController();
            Pasajesle p = new Pasajesle();
            pasajecontrol pc = new pasajecontrol();
            reservacioncontrol rc = new reservacioncontrol();

            for (int k = 0; k < pc.listar1().size(); k++) {
                Pasaje object2 = pc.listar1().get(k);
                if (object2.getViaje().getNroviaje() == nroviaje() && object2.getDisponibilidad().equals("si")) {
                    psobrant++;
                    p.setAsiento(object2.getNroasiento());
                    p.setDisponible("si");
                    p.setDiasalida(object2.getViaje().getDiasalida());
                    p.setHora(object2.getViaje().getHorasalida());
                    p.setMes(object2.getViaje().getMessalida());
                    p.setMin(object2.getViaje().getMinutosalida());
                    p.setPrecio(object2.getViaje().getPrecio());
                    p.setRuta(object2.getViaje().getRuta());
                    p.setYear(object2.getViaje().getYearsalida());
                    ple.create(p);
                    object2.setDisponibilidad("no");
                    pc.actualizar(object2);
                }

            }
            if(psobrant==0)
             JOptionPane.showMessageDialog(this, "No hay pasajes sobrantes");
            else{
             JOptionPane.showMessageDialog(this, "Los pasajes sobrantes han sido asignados a la LE");
        }
            jButton4.setVisible(false);
            jButton6.setVisible(true);
            }catch (negocio.jpa.exceptions.PreexistingEntityException ex) {
            Logger.getLogger(RectificarR.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(RectificarR.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         jButton4.setVisible(true);
          jButton3.setVisible(true);
          jButton1.setVisible(false);
          jButton2.setVisible(false);
          jComboBox1.setVisible(false);
          jLabel1.setVisible(false);
          jLabel2.setVisible(false);
          jLabel3.setVisible(false);
          jSpinner1.setVisible(false);
          jTextField1.setVisible(false);
          jButton5.setVisible(false);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
jList1.setVisible(true);
jButton7.setVisible(true);
jButton6.setVisible(false);


//Mostrar LE
/*PasajesleJpaController ple = new PasajesleJpaController();
Pasajesle p = new Pasajesle();
int cantp=0;
        for (int i = 0; i < ple.findPasajesleEntities().size(); i++) {
            Pasajesle object = ple.findPasajesleEntities().get(i);
             if(object.getDisponible().equals("si")){
                 cantp++;
             }

        }*/
Listaespera le = new Listaespera();
ListaesperaJpaController lejpa = new ListaesperaJpaController();
String array[]= new String[46];
Listaespera arrayle[]= new Listaespera[100];



int cont=0;
int nro=1;
   
if (String.valueOf(jComboBox1.getSelectedItem()).equals("Pinar del Rio")){
     for (int j = 0; j < lejpa.findListaesperaEntities().size(); j++) {
            Listaespera object = lejpa.findListaesperaEntities().get(j);
            if (object.getRuta().equals("Pinar del Rio")
                    && object.getNro()==nro){
                 array[j]=object.getCi()+"  "+object.getRuta()+" "+object.getNombre()+"  "+object.getNro();
arrayle[j]=object;
                 nro++;
                       cont++;
            }

     }
     //habana
     int nro2=1;
int cont2=0;
        for (int i = 0; i < lejpa.findListaesperaEntities().size(); i++) {
             Listaespera object2 = lejpa.findListaesperaEntities().get(i);
            if (object2.getRuta().equals("Habana")
                    && object2.getNro()==nro2){
                array[cont+i]=object2.getCi()+"  "+object2.getRuta()+"  "+object2.getNombre()+"  "+object2.getNro();
             nro2++;
             cont2++;
            }
        }
// Matanzas
 int nro3=1;
int cont3=0;
        for (int i = 0; i < lejpa.findListaesperaEntities().size(); i++) {
             Listaespera object2 = lejpa.findListaesperaEntities().get(i);
            if (object2.getRuta().equals("Matanzas")
                    && object2.getNro()==nro3){
                array[cont+i]=object2.getCi()+"  "+object2.getRuta()+"  "+object2.getNombre()+"  "+object2.getNro();
             nro3++;
             cont3++;
            }
        }
//Villa Clara
 int nro4=1;
int cont4=0;
        for (int i = 0; i < lejpa.findListaesperaEntities().size(); i++) {
             Listaespera object2 = lejpa.findListaesperaEntities().get(i);
            if (object2.getRuta().equals("Villa Clara")
                    && object2.getNro()==nro4){
                array[cont+i]=object2.getCi()+"  "+object2.getRuta()+"  "+object2.getNombre()+"  "+object2.getNro();
             nro4++;
             cont4++;
            }
        }
jList1.setListData(array);

}
    
//jList1.setListData(array);

//}
/*int pos=0;
for (int k = 0; k < 6; k++) {
            String object1 = destinocci[k];
            if(object1.equals(String.valueOf(jComboBox1.getSelectedItem()))){
                  pos=k;break;
            }

        }*/


/*if (String.valueOf(jComboBox1.getSelectedItem()).equals("Habana")){
    int nro2=1;
int cont2=0;
        for (int i = 0; i < lejpa.findListaesperaEntities().size(); i++) {
             Listaespera object2 = lejpa.findListaesperaEntities().get(i);
            if (object2.getRuta().equals("Habana")
                    && object2.getNro()==nro2){
                array[cont+i]=object2.getCi()+"  "+object2.getRuta()+"  "+object2.getNombre()+"  "+object2.getNro();
             nro2++;
             cont2++;
            }
        }
// Matanzas
 int nro3=1;
int cont3=0;
        for (int i = 0; i < lejpa.findListaesperaEntities().size(); i++) {
             Listaespera object2 = lejpa.findListaesperaEntities().get(i);
            if (object2.getRuta().equals("Matanzas")
                    && object2.getNro()==nro3){
                array[cont+i]=object2.getCi()+"  "+object2.getRuta()+"  "+object2.getNombre()+"  "+object2.getNro();
             nro3++;
             cont3++;
            }
        }
//Villa Clara
 int nro4=1;
int cont4=0;
        for (int i = 0; i < lejpa.findListaesperaEntities().size(); i++) {
             Listaespera object2 = lejpa.findListaesperaEntities().get(i);
            if (object2.getRuta().equals("Villa Clara")
                    && object2.getNro()==nro4){
                array[cont+i]=object2.getCi()+"  "+object2.getRuta()+"  "+object2.getNombre()+"  "+object2.getNro();
             nro4++;
             cont4++;
            }
             jList1.setListData(array);
        }

}
if (String.valueOf(jComboBox1.getSelectedItem()).equals("Matanzas")){
    // Matanzas
 int nro3=1;
int cont3=0;
        for (int i = 0; i < lejpa.findListaesperaEntities().size(); i++) {
             Listaespera object2 = lejpa.findListaesperaEntities().get(i);
            if (object2.getRuta().equals("Matanzas")
                    && object2.getNro()==nro3){
                array[cont+i]=object2.getCi()+"  "+object2.getRuta()+"  "+object2.getNombre()+"  "+object2.getNro();
             nro3++;
             cont3++;
            }
        }
//Villa Clara
 int nro4=1;
int cont4=0;
        for (int i = 0; i < lejpa.findListaesperaEntities().size(); i++) {
             Listaespera object2 = lejpa.findListaesperaEntities().get(i);
            if (object2.getRuta().equals("Villa Clara")
                    && object2.getNro()==nro4){
                array[cont+i]=object2.getCi()+"  "+object2.getRuta()+"  "+object2.getNombre()+"  "+object2.getNro();
             nro4++;
             cont4++;
            }
             jList1.setListData(array);
        }

}
if (String.valueOf(jComboBox1.getSelectedItem()).equals("Villa Clara")){
    int nro4=1;
int cont4=0;
        for (int i = 0; i < lejpa.findListaesperaEntities().size(); i++) {
             Listaespera object2 = lejpa.findListaesperaEntities().get(i);
            if (object2.getRuta().equals("Villa Clara")
                    && object2.getNro()==nro4){
                array[cont+i]=object2.getCi()+"  "+object2.getRuta()+"  "+object2.getNombre()+"  "+object2.getNro();
             nro4++;
             cont4++;
            }
             jList1.setListData(array);
        }

}*/
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jButton6.setVisible(false);
        String reserv[]= new String[46];
        PasajesleJpaController ple = new PasajesleJpaController();
Pasajesle p = new Pasajesle();
String rutas="";
double precio=0;
String ci="";
String nombre="";
int cont=0;
Listaespera le = new Listaespera();
ListaesperaJpaController lejpa = new ListaesperaJpaController();
        int pos=0;
        list=jList1.getSelectedValue();
   try {
          reserv[pos]=String.valueOf(list);
        //  pos++;
          //jTextField2.setText(reserv[0]);
          fecha fe=new fecha();
         // jTextField3.setText(reserv[1]);
          Reservacionle rle=new Reservacionle();
      //    jTextField2.setText(fe.ci(reserv[pos]));
          for (int j = 0; j < lejpa.findListaesperaEntities().size(); j++) {
                        Listaespera object1 = lejpa.findListaesperaEntities().get(j);
                        if (object1.getCi().equals(fe.ci(reserv[pos]))) {
                            rutas = object1.getRuta();
                            ci = object1.getCi();
                            nombre = object1.getNombre();
                            break;
                        }
                    }
          ReservacionleJpaController rlej=new ReservacionleJpaController();
          for (int i = 0; i < ple.findPasajesleEntities().size(); i++) {
            Pasajesle object = ple.findPasajesleEntities().get(i);
            if(object.getRuta().equals(String.valueOf(jComboBox1.getSelectedItem()))){
             
                    cont++;
                    rle.setAsiento(object.getAsiento());
                    rle.setCi(fe.ci(reserv[pos]));
                    rle.setDia(object.getDiasalida());
                    rle.setMes(object.getMes());
                    rle.setNombre(nombre);
                    rle.setPrecio(object.getPrecio());
                    rle.setRuta(rutas);
                    rle.setYear(object.getYear());
                    rlej.create(rle);
                //    jList1.setSelectedValue(reservada, rootPaneCheckingEnabled);
                    int idp = object.getIdpasajesle();
                    ple.destroy(idp);
                    lejpa.destroy(ci);
               JOptionPane.showMessageDialog(this, "La reservación se efectuó correctamente");break;
              
            
            }

          }
if (cont==0){
    JOptionPane.showMessageDialog(this, "Los pasajes se han terminado");
}
        /*  if (cont!=0){
              int nuevo=0;
              for (int k = 0; k < lejpa.findListaesperaEntities().size(); k++) {
                        Listaespera object2 = lejpa.findListaesperaEntities().get(k);
                        if (object2.getRuta().equals(String.valueOf(jComboBox1.getSelectedItem()))) {
                           nuevo=object2.getNro();
                           nuevo=nuevo-1;
                            le.setNro(nuevo);
                            lejpa.edit(le);

                        }
                    }
          }*/

      }catch (NonexistentEntityException ex) {
            Logger.getLogger(RectificarR.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(RectificarR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jList1.setVisible(true);
jButton7.setVisible(true);
jButton6.setVisible(false);
jButton9.setVisible(true);

Listaespera le = new Listaespera();
ListaesperaJpaController lejpa = new ListaesperaJpaController();
String array[]= new String[46];
Listaespera arrayle[]= new Listaespera[100];



int cont=0;
int nro=1;

//if (String.valueOf(jComboBox1.getSelectedItem()).equals("Pinar del Rio")){
     for (int j = 0; j < lejpa.findListaesperaEntities().size(); j++) {
            Listaespera object = lejpa.findListaesperaEntities().get(j);
            if (object.getRuta().equals(String.valueOf(jComboBox1.getSelectedItem()))
                    && object.getNro()==nro){
                 array[j]=object.getCi()+"  "+object.getRuta()+" "+object.getNombre()+"  "+object.getNro();
arrayle[j]=object;
                 nro++;
                       cont++;
            }

     }
    
jList1.setListData(array);

//}

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
       String reserv[]= new String[46];
        list=jList1.getSelectedValue();
        fecha fe = new fecha();
          reserv[0]=String.valueOf(list);
          String rutas="";
          int numero=0;
        ListaesperaJpaController le = new ListaesperaJpaController();
Listaespera l = new Listaespera();
        for (int i = 0; i < le.findListaesperaEntities().size(); i++) {
            l = le.findListaesperaEntities().get(i);
            if(l.getCi().equals(fe.ci(reserv[0]))){
                try {
                    rutas = l.getRuta();
                    le.destroy(fe.ci(reserv[0]));
                    for (int k = 0; k < le.findListaesperaEntities().size(); k++) {
                        Listaespera object1 = le.findListaesperaEntities().get(k);
                        if (object1.getRuta().equals(rutas)) {
                            numero=object1.getNro();
                            numero=numero-1;
                            object1.setNro(numero);
                            le.edit(object1);
                        }
                    }
                    JOptionPane.showMessageDialog(this, "El cliente fue eliminado de la lista de espera");break;
                } catch (Exception ex) {
                    Logger.getLogger(RectificarR.class.getName()).log(Level.SEVERE, null, ex);


            }
            }}
            

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        PasajesleJpaController ple = new PasajesleJpaController();
Pasajesle p = new Pasajesle();
int cantp=0;
        for (int i = 0; i < ple.findPasajesleEntities().size(); i++) {
            Pasajesle object = ple.findPasajesleEntities().get(i);
             if(object.getDisponible().equals("si")){
                 cantp++;
             }
        }
if(cantp==0){
    JOptionPane.showMessageDialog(this, "El viaje está completo");
}
if (cantp!=0){
    JOptionPane.showMessageDialog(this, "Agregue un nuevo destino"+" "+"Quedan"+" "+cantp+" "+"pasajes");
jComboBox2.setVisible(true);
jButton7.setVisible(false);
jButton8.setVisible(false);
jButton11.setVisible(true);
jButton12.setVisible(true);
jLabel5.setVisible(true);
}
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
           String reserv[]= new String[46];
        PasajesleJpaController ple = new PasajesleJpaController();
Pasajesle p = new Pasajesle();
String rutas="";
double precio=0;
String ci="";
String nombre="";
int cont=0;
Listaespera le = new Listaespera();
ListaesperaJpaController lejpa = new ListaesperaJpaController();
        int pos=0;
        list=jList1.getSelectedValue();
   try {
          reserv[pos]=String.valueOf(list);
        //  pos++;
          //jTextField2.setText(reserv[0]);
          fecha fe=new fecha();
         // jTextField3.setText(reserv[1]);
          Reservacionle rle=new Reservacionle();
      //    jTextField2.setText(fe.ci(reserv[pos]));
          for (int j = 0; j < lejpa.findListaesperaEntities().size(); j++) {
                        Listaespera object1 = lejpa.findListaesperaEntities().get(j);
                        if (object1.getCi().equals(fe.ci(reserv[pos]))) {
                            rutas = object1.getRuta();
                            ci = object1.getCi();
                            nombre = object1.getNombre();
                            break;
                        }
                    }
          ReservacionleJpaController rlej=new ReservacionleJpaController();
          for (int i = 0; i < ple.findPasajesleEntities().size(); i++) {
            Pasajesle object = ple.findPasajesleEntities().get(i);
            if(object.getRuta().equals(String.valueOf(jComboBox1.getSelectedItem()))){

                    cont++;
                    rle.setAsiento(object.getAsiento());
                    rle.setCi(fe.ci(reserv[pos]));
                    rle.setDia(object.getDiasalida());
                    rle.setMes(object.getMes());
                    rle.setNombre(nombre);
                    rle.setPrecio(object.getPrecio());
                    rle.setRuta(rutas);
                    rle.setYear(object.getYear());
                    rlej.create(rle);
                //    jList1.setSelectedValue(reservada, rootPaneCheckingEnabled);
                    int idp = object.getIdpasajesle();
                    ple.destroy(idp);
                    lejpa.destroy(ci);
               JOptionPane.showMessageDialog(this, "La reservación se efectuó correctamente");break;


            }

          }
if (cont==0){
    JOptionPane.showMessageDialog(this, "Los pasajes se han terminado");
}
        /*  if (cont!=0){
              int nuevo=0;
              for (int k = 0; k < lejpa.findListaesperaEntities().size(); k++) {
                        Listaespera object2 = lejpa.findListaesperaEntities().get(k);
                        if (object2.getRuta().equals(String.valueOf(jComboBox1.getSelectedItem()))) {
                           nuevo=object2.getNro();
                           nuevo=nuevo-1;
                            le.setNro(nuevo);
                            lejpa.edit(le);

                        }
                    }
          }*/

      }catch (NonexistentEntityException ex) {
            Logger.getLogger(RectificarR.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(RectificarR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        Listaespera le = new Listaespera();
ListaesperaJpaController lejpa = new ListaesperaJpaController();
String array[]= new String[46];
Listaespera arrayle[]= new Listaespera[100];



int cont=0;
int nro=1;

//if (String.valueOf(jComboBox1.getSelectedItem()).equals("Pinar del Rio")){
     for (int j = 0; j < lejpa.findListaesperaEntities().size(); j++) {
            Listaespera object = lejpa.findListaesperaEntities().get(j);
            if (object.getRuta().equals(String.valueOf(jComboBox2.getSelectedItem()))
                    && object.getNro()==nro){
                 array[j]=object.getCi()+"  "+object.getRuta()+" "+object.getNombre()+"  "+object.getNro();
arrayle[j]=object;
                 nro++;
                       cont++;
            }

     }

jList1.setListData(array);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try {
            // TODO add your handling code here:
               jTextField2.setText(String.valueOf(nroviaje()));
            int psobrant = 0;
            PasajesleJpaController ple = new PasajesleJpaController();
            Pasajesle p = new Pasajesle();
            //    pasajecontrol pc = new pasajecontrol();
            reservacioncontrol rc = new reservacioncontrol();
            for (int j = 0; j < rc.listar1().size(); j++) {
                Reservacion object3 = rc.listar1().get(j);
                if (object3.getViaje().getNroviaje() == nroviaje() && object3.getRectificada().equals("no")) {
                   
                    psobrant++;

                     p.setAsiento(object3.getAsiento());
                    p.setDisponible("si");
                    p.setDiasalida(object3.getDiasalida());
                    p.setHora(object3.getHorasalida());
                    p.setMes(object3.getMessalida());
                    p.setMin(object3.getMinutosalida());
                    p.setPrecio(object3.getPrecio());
                    p.setRuta(object3.getDestino());
                    p.setYear(object3.getYearsalida());
                    ple.create(p);
                 

                    object3.setRectificada("trasmitida");
                    rc.actualizar(object3);

                }
            }
        } catch (PreexistingEntityException ex) {
            Logger.getLogger(RectificarR.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(RectificarR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        PasajesleJpaController ple = new PasajesleJpaController();

        for (int i = 0; i < ple.findPasajesleEntities().size(); i++) {
            try {
                Pasajesle object = ple.findPasajesleEntities().get(i);
                ple.destroy(object.getIdpasajesle());

            } catch (NonexistentEntityException ex) {
                Logger.getLogger(RectificarR.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
         JOptionPane.showMessageDialog(this, "Viaje Listo");
         setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RectificarR dialog = new RectificarR(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
